<?php
/**
 * The source code of the Topics Summary widget.
 *
 * @package Log_Lolla_Pro
 * @since 1.0.0
 */

/**
 * The Topics Summary Widget.
 *
 * @package Log_Lolla_Pro
 * @since 1.0.0
 */
class Log_Lolla_Pro_Topics_Summary_Widget extends WP_Widget {
	/**
	 * Register Widget
	 */
	public function __construct() {
		parent::__construct(
			'log_lolla_pro_topics_summary_widget',
			'Log Lolla Pro ' . log_lolla_pro_get_topic_label( 'Topics Summary' ),
			array(
				/* translators: The Topics Summary widget description on the admin screen */
				'description'          => __( 'Display a short summary based on main topics', 'log_lolla_pro' ),
				/* translators: The Topics Summary widget `number of categories to use` text on the admin screen */
				'number_of_categories' => esc_html__( 'Number of categories to use', 'log_lolla_pro' ),
				/* translators: The Topics Summary widget `number of tags to use` text on the admin screen */
				'number_of_tags'       => esc_html__( 'Number of tags to use', 'log_lolla_pro' ),
				'classname'            => 'widget-log-lolla-pro widget-log-lolla-pro--topics-summary',
			)
		);
	}

	/**
	 * Display widget on frontend
	 *
	 * @param  array $args     The widget arguments.
	 * @param  array $instance The instance of the widget.
	 */
	public function widget( $args, $instance ) {
		$title   = apply_filters( 'widget_title', esc_html__( 'Topics Summary' ) );
		$url     = log_lolla_pro_get_link( 'Topics Summary' );
		$content = log_lolla_pro_get_topic_list_summary(
			$instance['number_of_categories'],
			$instance['number_of_tags']
		);

		if ( ! empty( $content ) ) {
			printf(
				'%1$s%2$s%3$s',
				wp_kses_post( $args['before_widget'] ),
				wp_kses_post( log_lolla_pro_display_widget( $title, $content, $url ) ),
				wp_kses_post( $args['after_widget'] )
			);
		}
	}

	/**
	 * Display widget on the backend
	 *
	 * @param  array $instance The widget instance.
	 */
	public function form( $instance ) {
		$form = '';

		$form .= '<p>';
		/* translators: The Topics Summary widget form help text on the admin screen */
		$form .= esc_html__( 'A description will be generated by merging the most popular category and tag descriptions', 'log-lolla-pro' );
		$form .= '</p>';

		$form .= '<p>';
		$form .= log_lolla_pro_display_widget_form_label( $this, 'number_of_categories' );
		$form .= '<br/>';
		$form .= log_lolla_pro_display_widget_form_input(
			$this,
			'number_of_categories',
			'number',
			$instance['number_of_categories']
		);
		$form .= '</p>';

		$form .= '<p>';
		$form .= log_lolla_pro_display_widget_form_label( $this, 'number_of_tags' );
		$form .= '<br/>';
		$form .= log_lolla_pro_display_widget_form_input(
			$this,
			'number_of_tags',
			'number',
			$instance['number_of_tags']
		);
		$form .= '</p>';

		global $log_lolla_pro_custom_kses_for_widgets;
		echo wp_kses( $form, $log_lolla_pro_custom_kses_for_widgets );
	}

	/**
	 * Process widget options to be saved
	 *
	 * @param  array $new_instance The new widget instance.
	 * @param  array $old_instance The old widget instance.
	 * @return array              An instance
	 */
	public function update( $new_instance, $old_instance ) {
		$instance = array();

		$instance['number_of_categories'] = ( ! empty( $new_instance['number_of_categories'] ) ) ? filter_var( $new_instance['number_of_categories'], FILTER_SANITIZE_NUMBER_INT ) : '0';
		$instance['number_of_tags']       = ( ! empty( $new_instance['number_of_tags'] ) ) ? filter_var( $new_instance['number_of_tags'], FILTER_SANITIZE_NUMBER_INT ) : '0';

		return $instance;
	}
}
add_action(
	'widgets_init', function() {
		register_widget( 'Log_Lolla_Pro_Topics_Summary_Widget' );
	}
);
